source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JCScrollViewBoundaryInspector_Example', :exclusive => true do
  pod "JCScrollViewBoundaryInspector", :path => "../"
end

target 'JCScrollViewBoundaryInspector_Tests', :exclusive => true do
  pod "JCScrollViewBoundaryInspector", :path => "../"

  
end
